import { CalculationResult } from '../types.ts';
import * as Finance from './calculators/finance.ts';
import * as Investment from './calculators/investment.ts';
import * as Business from './calculators/business.ts';
import * as Misc from './calculators/misc.ts';
import * as Health from './calculators/health.ts';
import * as MathLogic from './calculators/math.ts';
import * as Lifestyle from './calculators/lifestyle.ts';

// Re-export specific handlers for mapping
export const calculateEMI = Finance.calculateEMI;
export const calculateMortgage = Finance.calculateMortgage;
export const calculateDTI = Finance.calculateDTI;
export const calculateCarLoan = Finance.calculateCarLoan;
export const calculateCreditCardPayoff = Finance.calculateCreditCardPayoff;
export const calculateHomeAffordability = Finance.calculateHomeAffordability;
export const calculateRetirement = Finance.calculateRetirement;
export const calculateLoanPayoff = Finance.calculateLoanPayoff;
export const calculateRefinance = Finance.calculateRefinance;
export const calculateRentVsBuy = Finance.calculateRentVsBuy;
export const calculateBalloonLoan = Finance.calculateBalloonLoan;

export const calculateSIP = Investment.calculateSIP;
export const calculateCompoundInterest = Investment.calculateCompoundInterest;
export const calculateCAGR = Investment.calculateCAGR;
export const calculateFD = Investment.calculateFD;

export const calculateProfitMargin = Business.calculateProfitMargin;
export const calculateBreakEven = Business.calculateBreakEven;
export const calculateGST = Business.calculateGST;
export const calculateSalary = Business.calculateSalary;
export const calculateROI = Business.calculateROI;
export const calculateMarkup = Business.calculateMarkup;
export const calculateMarkupMargin = Business.calculateMarkupMargin;
export const calculateInventoryTurn = Business.calculateInventoryTurn;
export const calculateRetention = Business.calculateRetention;
export const calculateCommission = Business.calculateCommission;
export const calculateLTV = Business.calculateLTV;
export const calculateCAC = Business.calculateCAC;
export const calculateTip = Lifestyle.calculateTip;
export const calculateFuelCost = Lifestyle.calculateFuelCost;

export const calculateBMI = Misc.calculateBMI;
export const calculatePercentage = Misc.calculatePercentage;
export const calculateGPA = Misc.calculateGPA;
export const calculateAge = Misc.calculateAge;

export const calculateCalorie = Health.calculateCalorie;
export const calculateIdealWeight = Health.calculateIdealWeight;
export const calculateWaterIntake = Health.calculateWaterIntake;

export const calculateScientific = MathLogic.calculateScientific;
export const calculateProbability = MathLogic.calculateProbability;
export const calculateStats = MathLogic.calculateStats;
export const calculateCircleArea = MathLogic.calculateCircleArea;
export const calculateLengthConv = MathLogic.calculateLengthConv;
export const calculateRule72 = Investment.calculateRule72;

import * as Extras from './calculators/extras.ts';
export const calculateDebtToIncome = Extras.calculateDebtToIncome;
export const calculateFIRE = Extras.calculateFIRE;
export const calculateMonthlyBudget = Extras.calculateMonthlyBudget;
export const calculateInflation = Extras.calculateInflation;
export const calculateBodyFat = Extras.calculateBodyFat;
export const calculateLumpsum = Extras.calculateLumpsum;
export const calculateMutualFund = Extras.calculateMutualFund;
export const calculateBonusTax = Extras.calculateBonusTax;
export const calculatePropertyTax = Extras.calculatePropertyTax;
export const calculateCryptoROI = Extras.calculateCryptoROI;

export const calculateSimpleInterest = Extras.calculateSimpleInterest;
export const calculateSavingsGoal = Extras.calculateSavingsGoal;
export const calculateDiscount = Extras.calculateDiscount;
export const calculateDateDiff = Extras.calculateDateDiff;
export const calculateWorldClock = Extras.calculateWorldClock;
export const calculateFractionDecimal = Extras.calculateFractionDecimal;
export const calculateLease = Extras.calculateLease;
export const calculateHELOC = Extras.calculateHELOC;
export const calculateExponent = Extras.calculateExponent;
export const calculateLogarithm = Extras.calculateLogarithm;
export const calculateBasalMetabolic = Extras.calculateBasalMetabolic;
export const calculateWaistHip = Extras.calculateWaistHip;
export const calculateBinary = Extras.calculateBinary;
export const calculatePasswordStrength = Extras.calculatePasswordStrength;
export const calculateCountdown = Extras.calculateCountdown;
export const calculateSalaryComparison = Extras.calculateSalaryComparison;
export const calculateCarLease = Extras.calculateCarLease;
export const calculateStudentLoan = Extras.calculateStudentLoan;
export const calculateMacros = Extras.calculateMacros;
export const calculateUnitConverter = Extras.calculateUnitConverter;

import * as Batch from './calculators/batch.ts';
export const calculate_pregnancy_due_date = Batch.calculate_pregnancy_due_date;
export const calculate_ovulation = Batch.calculate_ovulation;
export const calculate_tdee = Batch.calculate_tdee;
export const calculate_one_rep_max = Batch.calculate_one_rep_max;
export const calculate_body_surface_area = Batch.calculate_body_surface_area;
export const calculate_pythagorean = Batch.calculate_pythagorean;
export const calculate_sphere_volume = Batch.calculate_sphere_volume;
export const calculate_cylinder_volume = Batch.calculate_cylinder_volume;
export const calculate_cone_volume = Batch.calculate_cone_volume;
export const calculate_quadratic_equation = Batch.calculate_quadratic_equation;
export const calculate_midpoint = Batch.calculate_midpoint;
export const calculate_distance_2d = Batch.calculate_distance_2d;
export const calculate_slope = Batch.calculate_slope;
export const calculate_factorial = Batch.calculate_factorial;
export const calculate_combinations = Batch.calculate_combinations;
export const calculate_permutations = Batch.calculate_permutations;
export const calculate_prime_factorization = Batch.calculate_prime_factorization;
export const calculate_gcd_lcm = Batch.calculate_gcd_lcm;
export const calculate_standard_deviation = Batch.calculate_standard_deviation;
export const calculate_kinetic_energy = Batch.calculate_kinetic_energy;
export const calculate_potential_energy = Batch.calculate_potential_energy;
export const calculate_ohm_law = Batch.calculate_ohm_law;
export const calculate_power = Batch.calculate_power;
export const calculate_density = Batch.calculate_density;
export const calculate_force = Batch.calculate_force;
export const calculate_speed_distance_time = Batch.calculate_speed_distance_time;
export const calculate_present_value = Batch.calculate_present_value;
export const calculate_future_value = Batch.calculate_future_value;
export const calculate_apy = Batch.calculate_apy;
export const calculate_current_yield = Batch.calculate_current_yield;
export const calculate_dividend_yield = Batch.calculate_dividend_yield;
export const calculate_wacc = Batch.calculate_wacc;
export const calculate_current_ratio = Batch.calculate_current_ratio;
export const calculate_quick_ratio = Batch.calculate_quick_ratio;
export const calculate_debt_to_equity = Batch.calculate_debt_to_equity;
export const calculate_bra_size = Batch.calculate_bra_size;
export const calculate_shoe_size_converter = Batch.calculate_shoe_size_converter;
export const calculate_temperature_converter = Batch.calculate_temperature_converter;
export const calculate_weight_converter = Batch.calculate_weight_converter;
export const calculate_data_storage_converter = Batch.calculate_data_storage_converter;
export const calculate_dog_age = Batch.calculate_dog_age;
export const calculate_cat_age = Batch.calculate_cat_age;
export const calculate_energy_cost = Batch.calculate_energy_cost;
export const calculate_pool_volume = Batch.calculate_pool_volume;
export const calculate_concrete_volume = Batch.calculate_concrete_volume;
export const calculate_paint = Batch.calculate_paint;
export const calculate_roofing = Batch.calculate_roofing;
export const calculate_z_score = Batch.calculate_z_score;
export const calculate_expected_value = Batch.calculate_expected_value;
export const calculate_roman_numerals = Batch.calculate_roman_numerals;

export const calculate_ratio = Batch.calculate_ratio;
export const calculate_percentage_diff = Batch.calculate_percentage_diff;
export const calculate_percentage_error = Batch.calculate_percentage_error;
export const calculate_fraction_decimal = Batch.calculate_fraction_decimal;
export const calculate_triangle_area = Batch.calculate_triangle_area;
export const calculate_rectangle_area = Batch.calculate_rectangle_area;
export const calculate_circle_circumference = Batch.calculate_circle_circumference;
export const calculate_arc_length = Batch.calculate_arc_length;
export const calculate_sector_area = Batch.calculate_sector_area;
export const calculate_sphere_surface_area = Batch.calculate_sphere_surface_area;
export const calculate_cylinder_surface_area = Batch.calculate_cylinder_surface_area;
export const calculate_box_surface_area = Batch.calculate_box_surface_area;
export const calculate_margin_of_error = Batch.calculate_margin_of_error;
export const calculate_rule_of_72 = Batch.calculate_rule_of_72;
export const calculate_sales_tax = Batch.calculate_sales_tax;
export const calculate_vat = Batch.calculate_vat;
export const calculate_profit_percentage = Batch.calculate_profit_percentage;
export const calculate_revenue = Batch.calculate_revenue;
export const calculate_net_income = Batch.calculate_net_income;
export const calculate_inventory_turnover = Batch.calculate_inventory_turnover;
export const calculate_days_in_inventory = Batch.calculate_days_in_inventory;
export const calculate_receivables_turnover = Batch.calculate_receivables_turnover;
export const calculate_return_on_assets = Batch.calculate_return_on_assets;
export const calculate_return_on_equity = Batch.calculate_return_on_equity;
export const calculate_calorie_deficit = Batch.calculate_calorie_deficit;
export const calculate_run_pace = Batch.calculate_run_pace;
export const calculate_ideal_weight = Batch.calculate_ideal_weight;
export const calculate_water_intake = Batch.calculate_water_intake;
export const calculate_blood_donation = Batch.calculate_blood_donation;
export const calculate_velocity_calc = Batch.calculate_velocity_calc;
export const calculate_torque_calc = Batch.calculate_torque_calc;
export const calculate_mass_energy = Batch.calculate_mass_energy;
export const calculate_hookes_law = Batch.calculate_hookes_law;
export const calculate_kinetic_friction = Batch.calculate_kinetic_friction;
export const calculate_escape_velocity = Batch.calculate_escape_velocity;
export const calculate_decimal_binary = Batch.calculate_decimal_binary;
export const calculate_decimal_hex = Batch.calculate_decimal_hex;
export const calculate_binary_decimal = Batch.calculate_binary_decimal;
export const calculate_hex_decimal = Batch.calculate_hex_decimal;
export const calculate_base64_encode = Batch.calculate_base64_encode;
export const calculate_words_calculator = Batch.calculate_words_calculator;
export const calculate_time_duration = Batch.calculate_time_duration;
export const calculate_days_between = Batch.calculate_days_between;
export const calculate_timestamp_date = Batch.calculate_timestamp_date;
export const calculate_adding_time = Batch.calculate_adding_time;
export const calculate_scientific_notation = Batch.calculate_scientific_notation;
export const calculate_molar_mass = Batch.calculate_molar_mass;
export const calculate_moles = Batch.calculate_moles;

export * as LogicBatch100 from './calculators/batch_100.ts';

export * as LogicBatchNew100 from './calculators/batch_new_100.ts';
