import fs from 'fs';

const batchCalcs = [
  // Math & Geometry
  { id: 'ratio', title: 'Ratio Calculator', category: 'math', inputs: [ { label: 'A', name: 'a', type: 'number', defaultValue: 16 }, { label: 'B', name: 'b', type: 'number', defaultValue: 9 }, { label: 'C', name: 'c', type: 'number', defaultValue: 1920 } ], logic: `const a=parseFloat(values.a); const b=parseFloat(values.b); const c=parseFloat(values.c); if(isNaN(a)||isNaN(b)||isNaN(c)||a===0) return []; return [{ label: 'Equivalent D', value: ((b/a)*c).toFixed(2), isPrimary: true }];` },
  { id: 'percentage-diff', title: 'Percentage Difference', category: 'math', inputs: [ { label: 'Value 1', name: 'v1', type: 'number', defaultValue: 100 }, { label: 'Value 2', name: 'v2', type: 'number', defaultValue: 120 } ], logic: `const v1=parseFloat(values.v1); const v2=parseFloat(values.v2); if(isNaN(v1)||isNaN(v2)) return []; const diff=Math.abs(v1-v2); const avg=(v1+v2)/2; return [{ label: 'Difference', value: ((diff/avg)*100).toFixed(2)+'%', isPrimary: true }];` },
  { id: 'percentage-error', title: 'Percentage Error', category: 'math', inputs: [ { label: 'Observed Value', name: 'o', type: 'number', defaultValue: 95 }, { label: 'Exact Value', name: 'e', type: 'number', defaultValue: 100 } ], logic: `const o=parseFloat(values.o); const e=parseFloat(values.e); if(isNaN(o)||isNaN(e)||e===0) return []; return [{ label: 'Percentage Error', value: (Math.abs((o-e)/e)*100).toFixed(2)+'%', isPrimary: true }];` },
  { id: 'fraction-decimal', title: 'Fraction to Decimal', category: 'math', inputs: [ { label: 'Numerator', name: 'n', type: 'number', defaultValue: 3 }, { label: 'Denominator', name: 'd', type: 'number', defaultValue: 4 } ], logic: `const n=parseFloat(values.n); const d=parseFloat(values.d); if(isNaN(n)||isNaN(d)||d===0) return []; return [{ label: 'Decimal', value: (n/d).toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'triangle-area', title: 'Triangle Area', category: 'math', inputs: [ { label: 'Base', name: 'b', type: 'number', defaultValue: 10 }, { label: 'Height', name: 'h', type: 'number', defaultValue: 5 } ], logic: `const b=parseFloat(values.b); const h=parseFloat(values.h); if(isNaN(b)||isNaN(h)) return []; return [{ label: 'Area', value: (0.5*b*h).toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'rectangle-area', title: 'Rectangle Area', category: 'math', inputs: [ { label: 'Length', name: 'l', type: 'number', defaultValue: 10 }, { label: 'Width', name: 'w', type: 'number', defaultValue: 5 } ], logic: `const l=parseFloat(values.l); const w=parseFloat(values.w); if(isNaN(l)||isNaN(w)) return []; return [{ label: 'Area', value: (l*w).toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'circle-circumference', title: 'Circle Circumference', category: 'math', inputs: [ { label: 'Radius', name: 'r', type: 'number', defaultValue: 5 } ], logic: `const r=parseFloat(values.r); if(isNaN(r)) return []; return [{ label: 'Circumference', value: (2*Math.PI*r).toPrecision(6).toString(), isPrimary: true }, { label: 'Area', value: (Math.PI*r*r).toPrecision(6).toString() }];` },
  { id: 'arc-length', title: 'Arc Length', category: 'math', inputs: [ { label: 'Radius', name: 'r', type: 'number', defaultValue: 5 }, { label: 'Central Angle (degrees)', name: 'a', type: 'number', defaultValue: 45 } ], logic: `const r=parseFloat(values.r); const a=parseFloat(values.a); if(isNaN(r)||isNaN(a)) return []; return [{ label: 'Arc Length', value: (2*Math.PI*r*(a/360)).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'sector-area', title: 'Sector Area', category: 'math', inputs: [ { label: 'Radius', name: 'r', type: 'number', defaultValue: 5 }, { label: 'Central Angle (degrees)', name: 'a', type: 'number', defaultValue: 45 } ], logic: `const r=parseFloat(values.r); const a=parseFloat(values.a); if(isNaN(r)||isNaN(a)) return []; return [{ label: 'Sector Area', value: (Math.PI*r*r*(a/360)).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'sphere-surface-area', title: 'Sphere Surface Area', category: 'math', inputs: [ { label: 'Radius', name: 'r', type: 'number', defaultValue: 5 } ], logic: `const r=parseFloat(values.r); if(isNaN(r)) return []; return [{ label: 'Surface Area', value: (4*Math.PI*r*r).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'cylinder-surface-area', title: 'Cylinder Surface Area', category: 'math', inputs: [ { label: 'Radius', name: 'r', type: 'number', defaultValue: 5 }, { label: 'Height', name: 'h', type: 'number', defaultValue: 10 } ], logic: `const r=parseFloat(values.r); const h=parseFloat(values.h); if(isNaN(r)||isNaN(h)) return []; return [{ label: 'Surface Area', value: (2*Math.PI*r*h + 2*Math.PI*r*r).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'box-surface-area', title: 'Box Surface Area', category: 'math', inputs: [ { label: 'Length', name: 'l', type: 'number', defaultValue: 5 }, { label: 'Width', name: 'w', type: 'number', defaultValue: 4 }, { label: 'Height', name: 'h', type: 'number', defaultValue: 3 } ], logic: `const l=parseFloat(values.l); const w=parseFloat(values.w); const h=parseFloat(values.h); if(isNaN(l)||isNaN(w)||isNaN(h)) return []; return [{ label: 'Surface Area', value: (2*(l*w + w*h + l*h)).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'margin-of-error', title: 'Margin of Error', category: 'math', inputs: [ { label: 'Z-Score (Confidence)', name: 'z', type: 'number', defaultValue: 1.96 }, { label: 'Population Std Dev', name: 's', type: 'number', defaultValue: 0.5 }, { label: 'Sample Size', name: 'n', type: 'number', defaultValue: 100 } ], logic: `const z=parseFloat(values.z); const s=parseFloat(values.s); const n=parseFloat(values.n); if(isNaN(z)||isNaN(s)||isNaN(n)||n<=0) return []; return [{ label: 'Margin of Error', value: (z*(s/Math.sqrt(n))).toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'rule-of-72', title: 'Rule of 72', category: 'finance', inputs: [ { label: 'Annual Interest Rate (%)', name: 'r', type: 'number', defaultValue: 8 } ], logic: `const r=parseFloat(values.r); if(isNaN(r)||r===0) return []; return [{ label: 'Years to Double', value: (72/r).toFixed(2), isPrimary: true }];` },
  { id: 'sales-tax', title: 'Sales Tax', category: 'tax', inputs: [ { label: 'Price before tax', name: 'p', type: 'number', defaultValue: 100 }, { label: 'Sales Tax Rate (%)', name: 'r', type: 'number', defaultValue: 7 } ], logic: `const p=parseFloat(values.p); const r=parseFloat(values.r)/100; if(isNaN(p)||isNaN(r)) return []; const t = p*r; return [{ label: 'Tax Amount', value: t.toFixed(2), isPrimary: true }, { label: 'Total Price', value: (p+t).toFixed(2) }];` },
  { id: 'vat', title: 'VAT Calculator', category: 'tax', inputs: [ { label: 'Net Price', name: 'p', type: 'number', defaultValue: 100 }, { label: 'VAT Rate (%)', name: 'r', type: 'number', defaultValue: 20 } ], logic: `const p=parseFloat(values.p); const r=parseFloat(values.r)/100; if(isNaN(p)||isNaN(r)) return []; const t = p*r; return [{ label: 'VAT Amount', value: t.toFixed(2), isPrimary: true }, { label: 'Gross Price', value: (p+t).toFixed(2) }];` },
  { id: 'profit-percentage', title: 'Profit Percentage', category: 'business', inputs: [ { label: 'Cost Price', name: 'c', type: 'number', defaultValue: 100 }, { label: 'Selling Price', name: 's', type: 'number', defaultValue: 150 } ], logic: `const c=parseFloat(values.c); const s=parseFloat(values.s); if(isNaN(c)||isNaN(s)||c===0) return []; return [{ label: 'Profit %', value: (((s-c)/c)*100).toFixed(2)+'%', isPrimary: true }];` },
  { id: 'revenue', title: 'Revenue Calculator', category: 'business', inputs: [ { label: 'Price per Unit', name: 'p', type: 'number', defaultValue: 50 }, { label: 'Units Sold', name: 'u', type: 'number', defaultValue: 1000 } ], logic: `const p=parseFloat(values.p); const u=parseFloat(values.u); if(isNaN(p)||isNaN(u)) return []; return [{ label: 'Total Revenue', value: (p*u).toFixed(2), isPrimary: true }];` },
  { id: 'net-income', title: 'Net Income', category: 'business', inputs: [ { label: 'Total Revenue', name: 'r', type: 'number', defaultValue: 50000 }, { label: 'Total Expenses', name: 'e', type: 'number', defaultValue: 30000 } ], logic: `const r=parseFloat(values.r); const e=parseFloat(values.e); if(isNaN(r)||isNaN(e)) return []; return [{ label: 'Net Income', value: (r-e).toFixed(2), isPrimary: true }];` },
  { id: 'inventory-turnover', title: 'Inventory Turnover', category: 'business', inputs: [ { label: 'Cost of Goods Sold', name: 'c', type: 'number', defaultValue: 100000 }, { label: 'Average Inventory', name: 'i', type: 'number', defaultValue: 20000 } ], logic: `const c=parseFloat(values.c); const i=parseFloat(values.i); if(isNaN(c)||isNaN(i)||i===0) return []; return [{ label: 'Turnover Ratio', value: (c/i).toFixed(2), isPrimary: true }];` },
  { id: 'days-in-inventory', title: 'Days in Inventory', category: 'business', inputs: [ { label: 'Average Inventory', name: 'i', type: 'number', defaultValue: 20000 }, { label: 'Cost of Goods Sold', name: 'c', type: 'number', defaultValue: 100000 } ], logic: `const i=parseFloat(values.i); const c=parseFloat(values.c); if(isNaN(i)||isNaN(c)||c===0) return []; return [{ label: 'Days in Inventory', value: ((i/c)*365).toFixed(2), isPrimary: true }];` },
  { id: 'receivables-turnover', title: 'Receivables Turnover', category: 'business', inputs: [ { label: 'Net Credit Sales', name: 's', type: 'number', defaultValue: 200000 }, { label: 'Average Acct Receivables', name: 'a', type: 'number', defaultValue: 40000 } ], logic: `const s=parseFloat(values.s); const a=parseFloat(values.a); if(isNaN(s)||isNaN(a)||a===0) return []; return [{ label: 'Turnover Ratio', value: (s/a).toFixed(2), isPrimary: true }];` },
  { id: 'return-on-assets', title: 'Return on Assets', category: 'business', inputs: [ { label: 'Net Income', name: 'i', type: 'number', defaultValue: 50000 }, { label: 'Total Assets', name: 'a', type: 'number', defaultValue: 500000 } ], logic: `const i=parseFloat(values.i); const a=parseFloat(values.a); if(isNaN(i)||isNaN(a)||a===0) return []; return [{ label: 'ROA', value: ((i/a)*100).toFixed(2)+'%', isPrimary: true }];` },
  { id: 'return-on-equity', title: 'Return on Equity (ROE)', category: 'business', inputs: [ { label: 'Net Income', name: 'i', type: 'number', defaultValue: 50000 }, { label: 'Shareholder Equity', name: 'e', type: 'number', defaultValue: 250000 } ], logic: `const i=parseFloat(values.i); const e=parseFloat(values.e); if(isNaN(i)||isNaN(e)||e===0) return []; return [{ label: 'ROE', value: ((i/e)*100).toFixed(2)+'%', isPrimary: true }];` },
  { id: 'calorie-deficit', title: 'Calorie Deficit', category: 'health', inputs: [ { label: 'TDEE (Maintenance Calories)', name: 'tdee', type: 'number', defaultValue: 2500 }, { label: 'Goal Weekly Loss (lbs)', name: 'w', type: 'number', defaultValue: 1 } ], logic: `const t=parseFloat(values.tdee); const w=parseFloat(values.w); if(isNaN(t)||isNaN(w)) return []; const deficit = (w * 3500) / 7; return [{ label: 'Daily Calorie Target', value: Math.round(t - deficit).toString(), isPrimary: true }, { label: 'Daily Deficit', value: Math.round(deficit).toString() }];` },
  { id: 'run-pace', title: 'Running Pace', category: 'health', inputs: [ { label: 'Distance (miles)', name: 'd', type: 'number', defaultValue: 3.1 }, { label: 'Time (minutes)', name: 't', type: 'number', defaultValue: 25 } ], logic: `const d=parseFloat(values.d); const t=parseFloat(values.t); if(isNaN(d)||isNaN(t)||d===0) return []; const p = t/d; const mins = Math.floor(p); const secs = Math.round((p-mins)*60); return [{ label: 'Pace (min/mi)', value: mins + ":" + (secs<10?"0"+secs:secs), isPrimary: true }];` },
  { id: 'ideal-weight', title: 'Ideal Weight', category: 'health', inputs: [ { label: 'Height (cm)', name: 'h', type: 'number', defaultValue: 175 }, { label: 'Gender', name: 'gender', type: 'select', defaultValue: 'male', options: [{label:'Male',value:'male'},{label:'Female',value:'female'}] } ], logic: `const h=parseFloat(values.h); const m=values.gender!=='female'; if(isNaN(h)) return []; const iw = m ? 50 + 0.91*(h-152.4) : 45.5 + 0.91*(h-152.4); return [{ label: 'Ideal Weight (kg)', value: iw.toFixed(1), isPrimary: true }];` },
  { id: 'water-intake', title: 'Water Intake', category: 'health', inputs: [ { label: 'Weight (kg)', name: 'w', type: 'number', defaultValue: 70 }, { label: 'Exercise Mins/Day', name: 'e', type: 'number', defaultValue: 30 } ], logic: `const w=parseFloat(values.w); const e=parseFloat(values.e); if(isNaN(w)||isNaN(e)) return []; const oz = (w*2.20462)*0.5 + (e/30)*12; const liters = oz * 0.0295735; return [{ label: 'Daily Water (Liters)', value: liters.toFixed(2), isPrimary: true }, { label: 'Daily Water (Oz)', value: oz.toFixed(0) }];` },
  { id: 'blood-donation', title: 'Blood Donation Date', category: 'health', inputs: [ { label: 'Last Donation Date', name: 'd', type: 'date', defaultValue: '2023-01-01' } ], logic: `const d=new Date(values.d).getTime(); if(isNaN(d)) return []; const next = new Date(d + 56 * 24 * 60 * 60 * 1000); return [{ label: 'Next Eligible Date', value: next.toDateString(), isPrimary: true }];` },
  { id: 'velocity-calc', title: 'Velocity (Distance/Time)', category: 'math', inputs: [ { label: 'Displacement (m)', name: 'd', type: 'number', defaultValue: 100 }, { label: 'Time (s)', name: 't', type: 'number', defaultValue: 10 } ], logic: `const d=parseFloat(values.d); const t=parseFloat(values.t); if(isNaN(d)||isNaN(t)||t===0) return []; return [{ label: 'Velocity (m/s)', value: (d/t).toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'torque-calc', title: 'Torque', category: 'math', inputs: [ { label: 'Force (N)', name: 'f', type: 'number', defaultValue: 50 }, { label: 'Radius (m)', name: 'r', type: 'number', defaultValue: 0.5 }, { label: 'Angle (degrees)', name: 'a', type: 'number', defaultValue: 90 } ], logic: `const f=parseFloat(values.f); const r=parseFloat(values.r); const a=parseFloat(values.a); if(isNaN(f)||isNaN(r)||isNaN(a)) return []; const t = r*f*Math.sin(a*(Math.PI/180)); return [{ label: 'Torque (N·m)', value: t.toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'mass-energy', title: 'E=mc²', category: 'math', inputs: [ { label: 'Mass (kg)', name: 'm', type: 'number', defaultValue: 1 } ], logic: `const m=parseFloat(values.m); if(isNaN(m)) return []; const c = 299792458; const e = m*c*c; return [{ label: 'Energy (Joules)', value: e.toExponential(4).toString(), isPrimary: true }];` },
  { id: 'hookes-law', title: 'Hookes Law', category: 'math', inputs: [ { label: 'Spring Constant (N/m)', name: 'k', type: 'number', defaultValue: 100 }, { label: 'Displacement (m)', name: 'x', type: 'number', defaultValue: 0.2 } ], logic: `const k=parseFloat(values.k); const x=parseFloat(values.x); if(isNaN(k)||isNaN(x)) return []; return [{ label: 'Restoring Force (N)', value: (-k*x).toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'kinetic-friction', title: 'Kinetic Friction', category: 'math', inputs: [ { label: 'Friction Coefficient (μk)', name: 'u', type: 'number', defaultValue: 0.5 }, { label: 'Normal Force (N)', name: 'n', type: 'number', defaultValue: 100 } ], logic: `const u=parseFloat(values.u); const n=parseFloat(values.n); if(isNaN(u)||isNaN(n)) return []; return [{ label: 'Kinetic Friction (N)', value: (u*n).toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'escape-velocity', title: 'Escape Velocity', category: 'math', inputs: [ { label: 'Mass of Body (kg)', name: 'm', type: 'number', defaultValue: 5.972e24 }, { label: 'Radius of Body (m)', name: 'r', type: 'number', defaultValue: 6.371e6 } ], logic: `const m=parseFloat(values.m); const r=parseFloat(values.r); if(isNaN(m)||isNaN(r)||r===0) return []; const G = 6.67430e-11; const v = Math.sqrt((2*G*m)/r); return [{ label: 'Escape Velocity (m/s)', value: v.toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'decimal-binary', title: 'Decimal to Binary', category: 'lifestyle', inputs: [ { label: 'Decimal Number', name: 'n', type: 'number', defaultValue: 42 } ], logic: `const n=parseInt(values.n); if(isNaN(n)) return []; return [{ label: 'Binary', value: n.toString(2), isPrimary: true }];` },
  { id: 'decimal-hex', title: 'Decimal to Hex', category: 'lifestyle', inputs: [ { label: 'Decimal Number', name: 'n', type: 'number', defaultValue: 255 } ], logic: `const n=parseInt(values.n); if(isNaN(n)) return []; return [{ label: 'Hexadecimal', value: n.toString(16).toUpperCase(), isPrimary: true }];` },
  { id: 'binary-decimal', title: 'Binary to Decimal', category: 'lifestyle', inputs: [ { label: 'Binary String', name: 'b', type: 'text', defaultValue: '101010' } ], logic: `if(!values.b) return []; const n = parseInt(values.b, 2); if(isNaN(n)) return []; return [{ label: 'Decimal', value: n.toString(), isPrimary: true }];` },
  { id: 'hex-decimal', title: 'Hex to Decimal', category: 'lifestyle', inputs: [ { label: 'Hex String', name: 'h', type: 'text', defaultValue: 'FF' } ], logic: `if(!values.h) return []; const n = parseInt(values.h, 16); if(isNaN(n)) return []; return [{ label: 'Decimal', value: n.toString(), isPrimary: true }];` },
  { id: 'base64-encode', title: 'Base64 Encode', category: 'lifestyle', inputs: [ { label: 'Text string', name: 't', type: 'text', defaultValue: 'Hello World' } ], logic: `if(!values.t) return []; try{ const b = btoa(values.t); return [{ label: 'Base64', value: b, isPrimary: true }]; }catch(e){return [];}` },
  { id: 'words-calculator', title: 'Word Count Calculator', category: 'lifestyle', inputs: [ { label: 'Text', name: 't', type: 'text', defaultValue: 'Type or paste your text here.' } ], logic: `if(!values.t) return []; const words = values.t.trim().split(/\\s+/).filter(w=>w.length>0).length; const chars = values.t.length; return [{ label: 'Word Count', value: words.toString(), isPrimary: true }, { label: 'Character Count', value: chars.toString() }];` },
  { id: 'time-duration', title: 'Time Duration', category: 'lifestyle', inputs: [ { label: 'Start Time (HH:MM)', name: 's', type: 'text', defaultValue: '09:00' }, { label: 'End Time (HH:MM)', name: 'e', type: 'text', defaultValue: '17:30' } ], logic: `if(!values.s||!values.e) return []; try{ const [h1,m1] = values.s.split(':').map(Number); const [h2,m2] = values.e.split(':').map(Number); let dMin = (h2*60 + m2) - (h1*60 + m1); if(dMin < 0) dMin += 24*60; return [{ label: 'Duration', value: Math.floor(dMin/60) + 'h ' + (dMin%60) + 'm', isPrimary: true }]; }catch(E){return [];}` },
  { id: 'days-between', title: 'Days Between', category: 'lifestyle', inputs: [ { label: 'Start Date', name: 's', type: 'date', defaultValue: '2023-01-01' }, { label: 'End Date', name: 'e', type: 'date', defaultValue: '2023-12-31' } ], logic: `try{ const d1 = new Date(values.s).getTime(); const d2 = new Date(values.e).getTime(); if(isNaN(d1)||isNaN(d2)) return []; const diff = Math.abs(d2-d1)/(1000*60*60*24); return [{ label: 'Days', value: Math.round(diff).toString(), isPrimary: true }]; }catch(e){return [];}` },
  { id: 'timestamp-date', title: 'Timestamp to Date', category: 'lifestyle', inputs: [ { label: 'Unix Timestamp Plugin (s/ms)', name: 't', type: 'number', defaultValue: 1672531200 } ], logic: `const t=parseFloat(values.t); if(isNaN(t)) return []; const ms = t < 1e12 ? t*1000 : t; return [{ label: 'Date', value: new Date(ms).toUTCString(), isPrimary: true }];` },
  { id: 'adding-time', title: 'Add Time', category: 'lifestyle', inputs: [ { label: 'Start Time (HH:MM)', name: 's', type: 'text', defaultValue: '09:00' }, { label: 'Add Hours', name: 'h', type: 'number', defaultValue: 2 }, { label: 'Add Minutes', name: 'm', type: 'number', defaultValue: 30 } ], logic: `if(!values.s) return []; const h=parseFloat(values.h)||0; const m=parseFloat(values.m)||0; try{ const [sh, sm] = values.s.split(':').map(Number); if(isNaN(sh)||isNaN(sm)) return []; let tMin = (sh*60 + sm) + (h*60 + m); tMin = tMin % (24*60); const oh=Math.floor(tMin/60); const om=tMin%60; return [{ label: 'New Time', value: oh.toString().padStart(2,'0') + ':' + om.toString().padStart(2,'0'), isPrimary: true }]; }catch(E){return [];}` },
  { id: 'scientific-notation', title: 'Scientific to Dec', category: 'math', inputs: [ { label: 'Value (e.g. 1.5e3)', name: 'v', type: 'text', defaultValue: '1.5e3' } ], logic: `if(!values.v) return []; const n=Number(values.v); if(isNaN(n)) return []; return [{ label: 'Decimal', value: n.toString(), isPrimary: true }];` },
  { id: 'molar-mass', title: 'Molar Mass (H2O)', category: 'math', inputs: [ { label: 'Moles', name: 'm', type: 'number', defaultValue: 2 } ], logic: `const m=parseFloat(values.m); if(isNaN(m)) return []; return [{ label: 'Mass of H2O (g)', value: (m*18.01528).toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'moles', title: 'Moles (H2O)', category: 'math', inputs: [ { label: 'Mass (g)', name: 'm', type: 'number', defaultValue: 36.03 } ], logic: `const m=parseFloat(values.m); if(isNaN(m)) return []; return [{ label: 'Moles', value: (m/18.01528).toPrecision(5).toString(), isPrimary: true }];` },
];

let constantsCode = fs.readFileSync('src/constants.ts', 'utf8');

const toInjectConstants = batchCalcs.map(c => 
  `  { id: '${c.id}', title: '${c.title}', slug: '${c.id}-calculator', description: '${c.title} calculator.', category: '${c.category}', priority: 'P3', icon: 'Calculator', formula: '', howItWorks: [], faqs: [], countryTips: [], relatedSlugs: [], seoTitle: '', seoDescription: '' },`
).join('\n');

constantsCode = constantsCode.replace(
  /export const CALCULATORS: CalculatorConfig\[\] = \[\n/,
  `export const CALCULATORS: CalculatorConfig[] = [\n` + toInjectConstants + `\n`
);
fs.writeFileSync('src/constants.ts', constantsCode);

let batchCode = fs.readFileSync('src/lib/calculators/batch.ts', 'utf8');
batchCalcs.forEach(c => {
  batchCode += `export function calculate_${c.id.replace(/-/g, '_')}(values: Record<string, any>): CalculationResult[] {\n  ${c.logic}\n}\n\n`;
});
fs.writeFileSync('src/lib/calculators/batch.ts', batchCode);

let logicIndex = fs.readFileSync('src/lib/calculatorLogic.ts', 'utf8');
let exportsLines = ``;
batchCalcs.forEach(c => {
  let fnName = `calculate_${c.id.replace(/-/g, '_')}`;
  exportsLines += `export const ${fnName} = Batch.${fnName};\n`;
});
logicIndex += `\n` + exportsLines;
fs.writeFileSync('src/lib/calculatorLogic.ts', logicIndex);

let detail = fs.readFileSync('src/pages/CalculatorDetail.tsx', 'utf8');

let newLogicMap = '';
let newInputMap = '';

batchCalcs.forEach(c => {
  let fnName = `calculate_${c.id.replace(/-/g, '_')}`;
  newLogicMap += `  '${c.id}': Logic.${fnName},\n`;
  
  newInputMap += `  '${c.id}': [\n`;
  c.inputs.forEach(i => {
    newInputMap += `    { label: '${i.label}', name: '${i.name}', type: '${i.type}', defaultValue: ${typeof i.defaultValue === 'string' ? '"'+i.defaultValue+'"' : i.defaultValue} ${i.options ? `, options: ${JSON.stringify(i.options)}` : ''} },\n`;
  });
  newInputMap += `  ],\n`;
});

detail = detail.replace(/const LOGIC_MAP: Record<([^>]+)> = \{/, "const LOGIC_MAP: Record<$1> = {\n" + newLogicMap);
detail = detail.replace(/const INPUT_MAP: Record<([^>]+)> = \{/, "const INPUT_MAP: Record<$1> = {\n" + newInputMap);

fs.writeFileSync('src/pages/CalculatorDetail.tsx', detail);
console.log('Batch 2 Done!');
