import fs from 'fs';

const batchCalcs = [
  { id: 'pregnancy-due-date', title: 'Due Date', category: 'health', inputs: [ { label: 'First Day of Last Period', name: 'lmp', type: 'date', defaultValue: '2023-01-01' } ], logic: `const lmpTime = new Date(values.lmp).getTime(); if (isNaN(lmpTime)) return []; const due = new Date(lmpTime + 280 * 24 * 60 * 60 * 1000); return [{ label: 'Estimated Due Date', value: due.toDateString(), isPrimary: true }];` },
  { id: 'ovulation', title: 'Ovulation', category: 'health', inputs: [ { label: 'First Day of Last Period', name: 'lmp', type: 'date', defaultValue: '2023-01-01' }, { label: 'Cycle Length (days)', name: 'cycle', type: 'number', defaultValue: 28 } ], logic: `const lmpTime = new Date(values.lmp).getTime(); const cycle = parseFloat(values.cycle); if (isNaN(lmpTime) || isNaN(cycle)) return []; const ovu = new Date(lmpTime + (cycle - 14) * 24 * 60 * 60 * 1000); return [{ label: 'Estimated Ovulation Date', value: ovu.toDateString(), isPrimary: true }];` },
  { id: 'tdee', title: 'TDEE', category: 'health', inputs: [ { label: 'Weight (kg)', name: 'weight', type: 'number', defaultValue: 70 }, { label: 'Height (cm)', name: 'height', type: 'number', defaultValue: 175 }, { label: 'Age', name: 'age', type: 'number', defaultValue: 25 }, { label: 'Gender', name: 'gender', type: 'select', defaultValue: 'male', options: [{label:'Male',value:'male'},{label:'Female',value:'female'}] }, { label: 'Activity Multiplier', name: 'activity', type: 'number', defaultValue: 1.2 } ], logic: `const w = parseFloat(values.weight); const h = parseFloat(values.height); const a = parseFloat(values.age); const m = values.gender !== 'female'; const act = parseFloat(values.activity); if(isNaN(w)||isNaN(h)||isNaN(a)||isNaN(act)) return []; const bmr = 10*w + 6.25*h - 5*a + (m?5:-161); return [{ label: 'TDEE (Calories/day)', value: Math.round(bmr*act).toString(), isPrimary: true }];` },
  { id: 'one-rep-max', title: 'One Rep Max (1RM)', category: 'health', inputs: [ { label: 'Weight Lifted', name: 'weight', type: 'number', defaultValue: 100 }, { label: 'Reps', name: 'reps', type: 'number', defaultValue: 5 } ], logic: `const w = parseFloat(values.weight); const r = parseFloat(values.reps); if(isNaN(w)||isNaN(r)||r<1) return []; const orm = w * (1 + r/30); return [{ label: 'Estimated 1RM', value: Math.round(orm).toString(), isPrimary: true }];` },
  { id: 'body-surface-area', title: 'BSA', category: 'health', inputs: [ { label: 'Weight (kg)', name: 'weight', type: 'number', defaultValue: 70 }, { label: 'Height (cm)', name: 'height', type: 'number', defaultValue: 175 } ], logic: `const w = parseFloat(values.weight); const h = parseFloat(values.height); if(isNaN(w)||isNaN(h)) return []; const bsa = Math.sqrt((w*h)/3600); return [{ label: 'Body Surface Area (m²)', value: bsa.toFixed(2), isPrimary: true }];` },
  { id: 'pythagorean', title: 'Pythagorean Theorem', category: 'math', inputs: [ { label: 'Side A', name: 'a', type: 'number', defaultValue: 3 }, { label: 'Side B', name: 'b', type: 'number', defaultValue: 4 } ], logic: `const a = parseFloat(values.a); const b = parseFloat(values.b); if(isNaN(a)||isNaN(b)) return []; return [{ label: 'Hypotenuse (C)', value: Math.sqrt(a*a + b*b).toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'sphere-volume', title: 'Sphere Volume', category: 'math', inputs: [ { label: 'Radius', name: 'r', type: 'number', defaultValue: 5 } ], logic: `const r = parseFloat(values.r); if(isNaN(r)) return []; return [{ label: 'Volume', value: ((4/3)*Math.PI*Math.pow(r,3)).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'cylinder-volume', title: 'Cylinder Volume', category: 'math', inputs: [ { label: 'Radius', name: 'r', type: 'number', defaultValue: 5 }, { label: 'Height', name: 'h', type: 'number', defaultValue: 10 } ], logic: `const r = parseFloat(values.r); const h = parseFloat(values.h); if(isNaN(r)||isNaN(h)) return []; return [{ label: 'Volume', value: (Math.PI*Math.pow(r,2)*h).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'cone-volume', title: 'Cone Volume', category: 'math', inputs: [ { label: 'Radius', name: 'r', type: 'number', defaultValue: 5 }, { label: 'Height', name: 'h', type: 'number', defaultValue: 10 } ], logic: `const r = parseFloat(values.r); const h = parseFloat(values.h); if(isNaN(r)||isNaN(h)) return []; return [{ label: 'Volume', value: ((1/3)*Math.PI*Math.pow(r,2)*h).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'quadratic-equation', title: 'Quadratic Equation solver', category: 'math', inputs: [ { label: 'a', name: 'a', type: 'number', defaultValue: 1 }, { label: 'b', name: 'b', type: 'number', defaultValue: -3 }, { label: 'c', name: 'c', type: 'number', defaultValue: 2 } ], logic: `const a = parseFloat(values.a); const b = parseFloat(values.b); const c = parseFloat(values.c); if(isNaN(a)||isNaN(b)||isNaN(c)) return []; const d = b*b - 4*a*c; if (d < 0) return [{ label: 'Roots', value: 'Complex roots', isPrimary: true }]; const r1 = (-b + Math.sqrt(d))/(2*a); const r2 = (-b - Math.sqrt(d))/(2*a); return [{ label: 'Root 1', value: r1.toString(), isPrimary: true }, { label: 'Root 2', value: r2.toString() }];` },
  { id: 'midpoint', title: 'Midpoint', category: 'math', inputs: [ { label: 'X1', name: 'x1', type: 'number', defaultValue: 0 }, { label: 'Y1', name: 'y1', type: 'number', defaultValue: 0 }, { label: 'X2', name: 'x2', type: 'number', defaultValue: 10 }, { label: 'Y2', name: 'y2', type: 'number', defaultValue: 10 } ], logic: `const x1=parseFloat(values.x1); const y1=parseFloat(values.y1); const x2=parseFloat(values.x2); const y2=parseFloat(values.y2); if(isNaN(x1)||isNaN(y1)||isNaN(x2)||isNaN(y2)) return []; return [{ label: 'Midpoint', value: (x1+x2)/2 + ", " + (y1+y2)/2, isPrimary: true }];` },
  { id: 'distance-2d', title: '2D Distance', category: 'math', inputs: [ { label: 'X1', name: 'x1', type: 'number', defaultValue: 0 }, { label: 'Y1', name: 'y1', type: 'number', defaultValue: 0 }, { label: 'X2', name: 'x2', type: 'number', defaultValue: 10 }, { label: 'Y2', name: 'y2', type: 'number', defaultValue: 10 } ], logic: `const x1=parseFloat(values.x1); const y1=parseFloat(values.y1); const x2=parseFloat(values.x2); const y2=parseFloat(values.y2); if(isNaN(x1)||isNaN(y1)||isNaN(x2)||isNaN(y2)) return []; const d = Math.sqrt(Math.pow(x2-x1, 2) + Math.pow(y2-y1, 2)); return [{ label: 'Distance', value: d.toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'slope', title: 'Slope', category: 'math', inputs: [ { label: 'X1', name: 'x1', type: 'number', defaultValue: 0 }, { label: 'Y1', name: 'y1', type: 'number', defaultValue: 0 }, { label: 'X2', name: 'x2', type: 'number', defaultValue: 10 }, { label: 'Y2', name: 'y2', type: 'number', defaultValue: 10 } ], logic: `const x1=parseFloat(values.x1); const y1=parseFloat(values.y1); const x2=parseFloat(values.x2); const y2=parseFloat(values.y2); if(isNaN(x1)||isNaN(y1)||isNaN(x2)||isNaN(y2)) return []; if (x1 === x2) return [{ label: 'Slope', value: 'Undefined (Vertical)', isPrimary: true }]; return [{ label: 'Slope', value: ((y2-y1)/(x2-x1)).toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'factorial', title: 'Factorial', category: 'math', inputs: [ { label: 'Number', name: 'n', type: 'number', defaultValue: 5 } ], logic: `const n = parseInt(values.n); if(isNaN(n) || n < 0) return []; let f = 1; for(let i=2; i<=n; i++) f*=i; return [{ label: 'Factorial', value: f.toString(), isPrimary: true }];` },
  { id: 'combinations', title: 'Combinations (nCr)', category: 'math', inputs: [ { label: 'n (total items)', name: 'n', type: 'number', defaultValue: 5 }, { label: 'r (items chosen)', name: 'r', type: 'number', defaultValue: 2 } ], logic: `const n = parseInt(values.n); const r = parseInt(values.r); if(isNaN(n)||isNaN(r)||n<0||r<0||r>n) return []; let f = 1; for(let i=1; i<=r; i++) { f = f * (n - i + 1) / i; } return [{ label: 'Combinations (nCr)', value: Math.round(f).toString(), isPrimary: true }];` },
  { id: 'permutations', title: 'Permutations (nPr)', category: 'math', inputs: [ { label: 'n (total items)', name: 'n', type: 'number', defaultValue: 5 }, { label: 'r (items chosen)', name: 'r', type: 'number', defaultValue: 2 } ], logic: `const n = parseInt(values.n); const r = parseInt(values.r); if(isNaN(n)||isNaN(r)||n<0||r<0||r>n) return []; let f = 1; for(let i=0; i<r; i++) { f = f * (n - i); } return [{ label: 'Permutations (nPr)', value: Math.round(f).toString(), isPrimary: true }];` },
  { id: 'prime-factorization', title: 'Prime Factorization', category: 'math', inputs: [ { label: 'Number', name: 'n', type: 'number', defaultValue: 60 } ], logic: `let n = parseInt(values.n); if(isNaN(n) || n < 2) return []; const factors = []; let d = 2; while (n > 1) { while (n % d === 0) { factors.push(d); n /= d; } d++; if (d * d > n && n > 1) { factors.push(n); break; } } return [{ label: 'Prime Factors', value: factors.join(' × '), isPrimary: true }];` },
  { id: 'gcd-lcm', title: 'GCD & LCM', category: 'math', inputs: [ { label: 'Number 1', name: 'a', type: 'number', defaultValue: 12 }, { label: 'Number 2', name: 'b', type: 'number', defaultValue: 15 } ], logic: `const a = parseInt(values.a); const b = parseInt(values.b); if(isNaN(a)||isNaN(b)||a<1||b<1) return []; const gcd = (x,y) => (!y ? x : gcd(y, x%y)); const g = gcd(a,b); const l = (a*b)/g; return [{ label: 'GCD', value: g.toString(), isPrimary: true }, { label: 'LCM', value: l.toString() }];` },
  { id: 'standard-deviation', title: 'Standard Deviation', category: 'math', inputs: [ { label: 'Comma Separated Values', name: 'vals', type: 'text', defaultValue: '10, 12, 23, 23, 16, 23, 21, 16' } ], logic: `if(!values.vals) return []; const arr = values.vals.split(',').map(v=>parseFloat(v.trim())).filter(v=>!isNaN(v)); if(arr.length < 2) return []; const mean = arr.reduce((a,b)=>a+b)/arr.length; const variance = arr.reduce((a,b)=>a+Math.pow(b-mean,2),0)/(arr.length-1); return [{ label: 'Sample Std Dev', value: Math.sqrt(variance).toPrecision(6).toString(), isPrimary: true }, { label: 'Variance', value: variance.toPrecision(6).toString() }];` },
  { id: 'kinetic-energy', title: 'Kinetic Energy', category: 'math', inputs: [ { label: 'Mass (kg)', name: 'm', type: 'number', defaultValue: 10 }, { label: 'Velocity (m/s)', name: 'v', type: 'number', defaultValue: 5 } ], logic: `const m = parseFloat(values.m); const v = parseFloat(values.v); if(isNaN(m)||isNaN(v)) return []; return [{ label: 'Kinetic Energy (J)', value: (0.5*m*v*v).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'potential-energy', title: 'Potential Energy', category: 'math', inputs: [ { label: 'Mass (kg)', name: 'm', type: 'number', defaultValue: 10 }, { label: 'Height (m)', name: 'h', type: 'number', defaultValue: 5 } ], logic: `const m = parseFloat(values.m); const h = parseFloat(values.h); if(isNaN(m)||isNaN(h)) return []; return [{ label: 'Potential Energy (J)', value: (m*9.81*h).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'ohm-law', title: 'Ohms Law', category: 'math', inputs: [ { label: 'Voltage (V)', name: 'v', type: 'number', defaultValue: '' }, { label: 'Current (A)', name: 'i', type: 'number', defaultValue: 5 }, { label: 'Resistance (Ω)', name: 'r', type: 'number', defaultValue: 10 } ], logic: `const v = parseFloat(values.v); const i = parseFloat(values.i); const r = parseFloat(values.r); if(isNaN(v) && !isNaN(i) && !isNaN(r)) return [{label: 'Voltage (V)', value: (i*r).toPrecision(5), isPrimary: true}]; if(!isNaN(v) && isNaN(i) && !isNaN(r)) return [{label: 'Current (A)', value: (v/r).toPrecision(5), isPrimary: true}]; if(!isNaN(v) && !isNaN(i) && isNaN(r)) return [{label: 'Resistance (Ω)', value: (v/i).toPrecision(5), isPrimary: true}]; return [{label: 'Error', value: 'Leave exactly one field empty'}];` },
  { id: 'power', title: 'Power (Electrical)', category: 'math', inputs: [ { label: 'Voltage (V)', name: 'v', type: 'number', defaultValue: 120 }, { label: 'Current (A)', name: 'i', type: 'number', defaultValue: 15 } ], logic: `const v = parseFloat(values.v); const i = parseFloat(values.i); if(isNaN(v)||isNaN(i)) return []; return [{ label: 'Power (W)', value: (v*i).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'density', title: 'Density', category: 'math', inputs: [ { label: 'Mass (kg)', name: 'm', type: 'number', defaultValue: 100 }, { label: 'Volume (m³)', name: 'v', type: 'number', defaultValue: 2 } ], logic: `const m = parseFloat(values.m); const v = parseFloat(values.v); if(isNaN(m)||isNaN(v)||v===0) return []; return [{ label: 'Density (kg/m³)', value: (m/v).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'force', title: 'Force (F=ma)', category: 'math', inputs: [ { label: 'Mass (kg)', name: 'm', type: 'number', defaultValue: 10 }, { label: 'Acceleration (m/s²)', name: 'a', type: 'number', defaultValue: 9.8 } ], logic: `const m = parseFloat(values.m); const a = parseFloat(values.a); if(isNaN(m)||isNaN(a)) return []; return [{ label: 'Force (N)', value: (m*a).toPrecision(6).toString(), isPrimary: true }];` },
  { id: 'speed-distance-time', title: 'Speed / Dist / Time', category: 'math', inputs: [ { label: 'Distance', name: 'd', type: 'number', defaultValue: '' }, { label: 'Speed', name: 's', type: 'number', defaultValue: 60 }, { label: 'Time', name: 't', type: 'number', defaultValue: 2 } ], logic: `const d=parseFloat(values.d); const s=parseFloat(values.s); const t=parseFloat(values.t); if(isNaN(d)&&!isNaN(s)&&!isNaN(t)) return [{label: 'Distance', value: (s*t).toPrecision(5), isPrimary:true}]; if(!isNaN(d)&&isNaN(s)&&!isNaN(t)) return [{label: 'Speed', value: (d/t).toPrecision(5), isPrimary:true}]; if(!isNaN(d)&&!isNaN(s)&&isNaN(t)) return [{label: 'Time', value: (d/s).toPrecision(5), isPrimary:true}]; return [{label: 'Error', value: 'Leave exactly ONE blank'}];` },
  { id: 'present-value', title: 'Present Value', category: 'finance', inputs: [ { label: 'Future Value', name: 'fv', type: 'number', defaultValue: 10000 }, { label: 'Rate (%)', name: 'r', type: 'number', defaultValue: 5 }, { label: 'Periods', name: 'n', type: 'number', defaultValue: 5 } ], logic: `const fv=parseFloat(values.fv); const r=parseFloat(values.r)/100; const n=parseFloat(values.n); if(isNaN(fv)||isNaN(r)||isNaN(n)) return []; return [{ label: 'Present Value', value: (fv/Math.pow(1+r, n)).toFixed(2), isPrimary: true }];` },
  { id: 'future-value', title: 'Future Value', category: 'finance', inputs: [ { label: 'Present Value', name: 'pv', type: 'number', defaultValue: 10000 }, { label: 'Rate (%)', name: 'r', type: 'number', defaultValue: 5 }, { label: 'Periods', name: 'n', type: 'number', defaultValue: 5 } ], logic: `const pv=parseFloat(values.pv); const r=parseFloat(values.r)/100; const n=parseFloat(values.n); if(isNaN(pv)||isNaN(r)||isNaN(n)) return []; return [{ label: 'Future Value', value: (pv*Math.pow(1+r, n)).toFixed(2), isPrimary: true }];` },
  { id: 'apy', title: 'APY Calculator', category: 'finance', inputs: [ { label: 'Stated Rate (APR) %', name: 'apr', type: 'number', defaultValue: 5 }, { label: 'Compounds per year', name: 'n', type: 'number', defaultValue: 12 } ], logic: `const apr=parseFloat(values.apr)/100; const n=parseFloat(values.n); if(isNaN(apr)||isNaN(n)) return []; const apy = Math.pow(1 + apr/n, n) - 1; return [{ label: 'APY', value: (apy*100).toFixed(3)+'%', isPrimary: true }];` },
  { id: 'current-yield', title: 'Current Yield (Bond)', category: 'finance', inputs: [ { label: 'Annual Coupon Payment', name: 'c', type: 'number', defaultValue: 50 }, { label: 'Current Bond Price', name: 'p', type: 'number', defaultValue: 950 } ], logic: `const c=parseFloat(values.c); const p=parseFloat(values.p); if(isNaN(c)||isNaN(p)) return []; return [{ label: 'Current Yield', value: ((c/p)*100).toFixed(2)+'%', isPrimary: true }];` },
  { id: 'dividend-yield', title: 'Dividend Yield', category: 'finance', inputs: [ { label: 'Annual Dividend Per Share', name: 'd', type: 'number', defaultValue: 2.50 }, { label: 'Share Price', name: 'p', type: 'number', defaultValue: 50 } ], logic: `const d=parseFloat(values.d); const p=parseFloat(values.p); if(isNaN(d)||isNaN(p)) return []; return [{ label: 'Dividend Yield', value: ((d/p)*100).toFixed(2)+'%', isPrimary: true }];` },
  { id: 'wacc', title: 'WACC', category: 'business', inputs: [ { label: 'Equity Value', name: 'e', type: 'number', defaultValue: 600000 }, { label: 'Debt Value', name: 'd', type: 'number', defaultValue: 400000 }, { label: 'Cost of Equity (%)', name: 'ce', type: 'number', defaultValue: 10 }, { label: 'Cost of Debt (%)', name: 'cd', type: 'number', defaultValue: 5 }, { label: 'Corporate Tax Rate (%)', name: 't', type: 'number', defaultValue: 21 } ], logic: `const e=parseFloat(values.e); const d=parseFloat(values.d); const ce=parseFloat(values.ce)/100; const cd=parseFloat(values.cd)/100; const t=parseFloat(values.t)/100; if(isNaN(e)||isNaN(d)||isNaN(ce)||isNaN(cd)||isNaN(t)) return []; const v = e+d; if(v===0) return []; const wacc = (e/v)*ce + (d/v)*cd*(1-t); return [{ label: 'WACC', value: (wacc*100).toFixed(2)+'%', isPrimary: true }];` },
  { id: 'current-ratio', title: 'Current Ratio', category: 'business', inputs: [ { label: 'Current Assets', name: 'a', type: 'number', defaultValue: 150000 }, { label: 'Current Liabilities', name: 'l', type: 'number', defaultValue: 100000 } ], logic: `const a=parseFloat(values.a); const l=parseFloat(values.l); if(isNaN(a)||isNaN(l)||l===0) return []; return [{ label: 'Current Ratio', value: (a/l).toFixed(2), isPrimary: true }];` },
  { id: 'quick-ratio', title: 'Quick Ratio', category: 'business', inputs: [ { label: 'Current Assets', name: 'a', type: 'number', defaultValue: 150000 }, { label: 'Inventory', name: 'i', type: 'number', defaultValue: 50000 }, { label: 'Current Liabilities', name: 'l', type: 'number', defaultValue: 100000 } ], logic: `const a=parseFloat(values.a); const i=parseFloat(values.i); const l=parseFloat(values.l); if(isNaN(a)||isNaN(i)||isNaN(l)||l===0) return []; return [{ label: 'Quick Ratio', value: ((a-i)/l).toFixed(2), isPrimary: true }];` },
  { id: 'debt-to-equity', title: 'Debt to Equity', category: 'business', inputs: [ { label: 'Total Liabilities', name: 'l', type: 'number', defaultValue: 200000 }, { label: 'Total Shareholder Equity', name: 'e', type: 'number', defaultValue: 500000 } ], logic: `const l=parseFloat(values.l); const e=parseFloat(values.e); if(isNaN(l)||isNaN(e)||e===0) return []; return [{ label: 'D/E Ratio', value: (l/e).toFixed(2), isPrimary: true }];` },
  { id: 'bra-size', title: 'Bra Size', category: 'lifestyle', inputs: [ { label: 'Underbust (inches)', name: 'u', type: 'number', defaultValue: 32 }, { label: 'Bust (inches)', name: 'b', type: 'number', defaultValue: 36 } ], logic: `const u=parseFloat(values.u); const b=parseFloat(values.b); if(isNaN(u)||isNaN(b)) return []; let band = Math.round(u); if(band%2!==0) band+=1; const diff = b - band; const cups = ['AA','A','B','C','D','DD','E','F','FF','G']; let cup = diff < 0 ? 'AA' : cups[diff] || 'Unknown'; return [{ label: 'Estimated Size', value: band + cup, isPrimary: true }];` },
  { id: 'shoe-size-converter', title: 'Shoe Size Converter', category: 'lifestyle', inputs: [ { label: 'US Size (Men)', name: 'us', type: 'number', defaultValue: 10 } ], logic: `const us = parseFloat(values.us); if(isNaN(us)) return []; return [{ label: 'UK Size', value: (us - 1).toString(), isPrimary: true }, { label: 'EU Size (approx)', value: Math.round(33 + (us * 1.33)).toString() }];` },
  { id: 'temperature-converter', title: 'Temp Converter', category: 'lifestyle', inputs: [ { label: 'Temp', name: 't', type: 'number', defaultValue: 0 }, { label: 'From Unit', name: 'from', type: 'select', defaultValue: 'c', options: [{label:'Celsius', value:'c'},{label:'Fahrenheit',value:'f'},{label:'Kelvin',value:'k'}] } ], logic: `const t = parseFloat(values.t); const f = values.from; if(isNaN(t)) return []; let c = t; if(f==='f') c = (t-32)*5/9; if(f==='k') c = t - 273.15; return [{ label: 'Celsius', value: c.toFixed(2)+' °C', isPrimary: true }, { label: 'Fahrenheit', value: (c*9/5 + 32).toFixed(2)+' °F' }, { label: 'Kelvin', value: (c+273.15).toFixed(2)+' K' }];` },
  { id: 'weight-converter', title: 'Weight Converter', category: 'lifestyle', inputs: [ { label: 'Weight', name: 'w', type: 'number', defaultValue: 1 }, { label: 'From Unit', name: 'from', type: 'select', defaultValue: 'kg', options: [{label:'Kilograms', value:'kg'},{label:'Pounds',value:'lb'}] } ], logic: `const w = parseFloat(values.w); const f = values.from; if(isNaN(w)) return []; let kg = f==='lb' ? w*0.453592 : w; return [{ label: 'Kilograms', value: kg.toFixed(2), isPrimary: true }, { label: 'Pounds', value: (kg*2.20462).toFixed(2) }];` },
  { id: 'data-storage-converter', title: 'Data Converter', category: 'lifestyle', inputs: [ { label: 'Gigabytes (GB)', name: 'gb', type: 'number', defaultValue: 1 } ], logic: `const gb = parseFloat(values.gb); if(isNaN(gb)) return []; return [{ label: 'Megabytes (MB)', value: (gb*1024).toString(), isPrimary: true }, { label: 'Terabytes (TB)', value: (gb/1024).toPrecision(5).toString() }];` },
  { id: 'dog-age', title: 'Dog Age', category: 'lifestyle', inputs: [ { label: 'Dog Years', name: 'd', type: 'number', defaultValue: 5 } ], logic: `const d=parseFloat(values.d); if(isNaN(d)) return []; let h = d<=2 ? d*10.5 : 21 + (d-2)*4; return [{ label: 'Human Years', value: h.toString(), isPrimary: true }];` },
  { id: 'cat-age', title: 'Cat Age', category: 'lifestyle', inputs: [ { label: 'Cat Years', name: 'c', type: 'number', defaultValue: 5 } ], logic: `const c=parseFloat(values.c); if(isNaN(c)) return []; let h = c===1 ? 15 : (c===2 ? 24 : 24 + (c-2)*4); return [{ label: 'Human Years', value: h.toString(), isPrimary: true }];` },
  { id: 'energy-cost', title: 'Energy Cost', category: 'lifestyle', inputs: [ { label: 'Power (Watts)', name: 'w', type: 'number', defaultValue: 1000 }, { label: 'Hours per Day', name: 'h', type: 'number', defaultValue: 2 }, { label: 'Cost per kWh ($)', name: 'c', type: 'number', defaultValue: 0.15 } ], logic: `const w = parseFloat(values.w); const h = parseFloat(values.h); const c = parseFloat(values.c); if(isNaN(w)||isNaN(h)||isNaN(c)) return []; const cost = (w/1000)*h*c*30; return [{ label: 'Monthly Cost', value: cost.toFixed(2), isPrimary: true }];` },
  { id: 'pool-volume', title: 'Pool Volume', category: 'lifestyle', inputs: [ { label: 'Length (ft)', name: 'l', type: 'number', defaultValue: 20 }, { label: 'Width (ft)', name: 'w', type: 'number', defaultValue: 10 }, { label: 'Average Depth (ft)', name: 'd', type: 'number', defaultValue: 5 } ], logic: `const l = parseFloat(values.l); const w = parseFloat(values.w); const d = parseFloat(values.d); if(isNaN(l)||isNaN(w)||isNaN(d)) return []; const gallons = l*w*d*7.5; return [{ label: 'Volume (Gallons)', value: Math.round(gallons).toString(), isPrimary: true }];` },
  { id: 'concrete-volume', title: 'Concrete Calculator', category: 'lifestyle', inputs: [ { label: 'Length (ft)', name: 'l', type: 'number', defaultValue: 10 }, { label: 'Width (ft)', name: 'w', type: 'number', defaultValue: 10 }, { label: 'Thickness (in)', name: 't', type: 'number', defaultValue: 4 } ], logic: `const l = parseFloat(values.l); const w = parseFloat(values.w); const t = parseFloat(values.t); if(isNaN(l)||isNaN(w)||isNaN(t)) return []; const yards = (l*w*(t/12))/27; return [{ label: 'Concrete Needed (Cubic Yards)', value: yards.toFixed(2), isPrimary: true }];` },
  { id: 'paint', title: 'Paint Calculator', category: 'lifestyle', inputs: [ { label: 'Wall Length (ft)', name: 'l', type: 'number', defaultValue: 12 }, { label: 'Wall Height (ft)', name: 'h', type: 'number', defaultValue: 8 } ], logic: `const l = parseFloat(values.l); const h = parseFloat(values.h); if(isNaN(l)||isNaN(h)) return []; const sqft = l*h; return [{ label: 'Paint Needed (Gallons)', value: (sqft/350).toFixed(2), isPrimary: true }];` },
  { id: 'roofing', title: 'Roofing Calculator', category: 'lifestyle', inputs: [ { label: 'Roof Area (sq ft)', name: 'a', type: 'number', defaultValue: 1500 } ], logic: `const a = parseFloat(values.a); if(isNaN(a)) return []; const squares = a/100; return [{ label: 'Roofing Squares needed', value: Math.ceil(squares).toString(), isPrimary: true }];` },
  { id: 'z-score', title: 'Z-Score', category: 'math', inputs: [ { label: 'Value (X)', name: 'x', type: 'number', defaultValue: 50 }, { label: 'Mean (μ)', name: 'm', type: 'number', defaultValue: 40 }, { label: 'Std Dev (σ)', name: 's', type: 'number', defaultValue: 5 } ], logic: `const x=parseFloat(values.x); const m=parseFloat(values.m); const s=parseFloat(values.s); if(isNaN(x)||isNaN(m)||isNaN(s)||s===0) return []; return [{ label: 'Z-Score', value: ((x-m)/s).toFixed(3), isPrimary: true }];` },
  { id: 'expected-value', title: 'Expected Value', category: 'math', inputs: [ { label: 'Values (Comma space separated)', name: 'v', type: 'text', defaultValue: '10, 20' }, { label: 'Probabilities (Comma space separated, decimals)', name: 'p', type: 'text', defaultValue: '0.5, 0.5' } ], logic: `if(!values.v||!values.p) return []; const val = values.v.split(',').map(x=>parseFloat(x.trim())); const pb = values.p.split(',').map(x=>parseFloat(x.trim())); if(val.length !== pb.length || val.some(isNaN) || pb.some(isNaN)) return []; let ev = 0; for(let i=0; i<val.length; i++) ev += val[i]*pb[i]; return [{ label: 'Expected Value', value: ev.toPrecision(5).toString(), isPrimary: true }];` },
  { id: 'roman-numerals', title: 'Roman Numerals', category: 'lifestyle', inputs: [ { label: 'Number', name: 'n', type: 'number', defaultValue: 2024 } ], logic: `let n = parseInt(values.n); if(isNaN(n) || n < 1 || n > 3999) return []; const val = [1000,900,500,400,100,90,50,40,10,9,5,4,1]; const s = ["M","CM","D","CD","C","XC","L","XL","X","IX","V","IV","I"]; let rn = ""; for(let i=0; i<val.length; i++){ while(n >= val[i]){ rn += s[i]; n -= val[i]; } } return [{ label: 'Roman Numeral', value: rn, isPrimary: true }];` },
];

let constantsCode = fs.readFileSync('src/constants.ts', 'utf8');

const toInjectConstants = batchCalcs.map(c => 
  `  { id: '${c.id}', title: '${c.title}', slug: '${c.id}-calculator', description: '${c.title} calculator.', category: '${c.category}', priority: 'P3', icon: 'Calculator', formula: '', howItWorks: [], faqs: [], countryTips: [], relatedSlugs: [], seoTitle: '', seoDescription: '' },`
).join('\n');

constantsCode = constantsCode.replace(
  /export const CALCULATORS: CalculatorConfig\[\] = \[\n/,
  `export const CALCULATORS: CalculatorConfig[] = [\n` + toInjectConstants + `\n`
);
fs.writeFileSync('src/constants.ts', constantsCode);

let batchCode = `import { CalculationResult } from '../../types.ts';\n\n`;
batchCalcs.forEach(c => {
  batchCode += `export function calculate_${c.id.replace(/-/g, '_')}(values: Record<string, any>): CalculationResult[] {\n  ${c.logic}\n}\n\n`;
});
fs.writeFileSync('src/lib/calculators/batch.ts', batchCode);

let logicIndex = fs.readFileSync('src/lib/calculatorLogic.ts', 'utf8');
let exportsLines = `import * as Batch from './calculators/batch.ts';\n`;
batchCalcs.forEach(c => {
  let fnName = `calculate_${c.id.replace(/-/g, '_')}`;
  exportsLines += `export const ${fnName} = Batch.${fnName};\n`;
});
logicIndex += `\n` + exportsLines;
fs.writeFileSync('src/lib/calculatorLogic.ts', logicIndex);

let detail = fs.readFileSync('src/pages/CalculatorDetail.tsx', 'utf8');

let newLogicMap = '';
let newInputMap = '';

batchCalcs.forEach(c => {
  let fnName = `calculate_${c.id.replace(/-/g, '_')}`;
  newLogicMap += `  '${c.id}': Logic.${fnName},\n`;
  
  newInputMap += `  '${c.id}': [\n`;
  c.inputs.forEach(i => {
    newInputMap += `    { label: '${i.label}', name: '${i.name}', type: '${i.type}', defaultValue: ${typeof i.defaultValue === 'string' ? '"'+i.defaultValue+'"' : i.defaultValue} ${i.options ? `, options: ${JSON.stringify(i.options)}` : ''} },\n`;
  });
  newInputMap += `  ],\n`;
});

detail = detail.replace(/const LOGIC_MAP: Record<([^>]+)> = \{/, "const LOGIC_MAP: Record<$1> = {\n" + newLogicMap);
detail = detail.replace(/const INPUT_MAP: Record<([^>]+)> = \{/, "const INPUT_MAP: Record<$1> = {\n" + newInputMap);

fs.writeFileSync('src/pages/CalculatorDetail.tsx', detail);
console.log('Done!');
