import fs from 'fs';

const c1 = [
  { id: 'pregnancy-due-date', title: 'Due Date', category: 'health'},
  { id: 'ovulation', title: 'Ovulation', category: 'health'},
  { id: 'tdee', title: 'TDEE', category: 'health'},
  { id: 'one-rep-max', title: 'One Rep Max (1RM)', category: 'health'},
  { id: 'body-surface-area', title: 'BSA', category: 'health'},
  { id: 'pythagorean', title: 'Pythagorean Theorem', category: 'math'},
  { id: 'sphere-volume', title: 'Sphere Volume', category: 'math'},
  { id: 'cylinder-volume', title: 'Cylinder Volume', category: 'math'},
  { id: 'cone-volume', title: 'Cone Volume', category: 'math'},
  { id: 'quadratic-equation', title: 'Quadratic Equation solver', category: 'math'},
  { id: 'midpoint', title: 'Midpoint', category: 'math'},
  { id: 'distance-2d', title: '2D Distance', category: 'math'},
  { id: 'slope', title: 'Slope', category: 'math'},
  { id: 'factorial', title: 'Factorial', category: 'math'},
  { id: 'combinations', title: 'Combinations (nCr)', category: 'math'},
  { id: 'permutations', title: 'Permutations (nPr)', category: 'math'},
  { id: 'prime-factorization', title: 'Prime Factorization', category: 'math'},
  { id: 'gcd-lcm', title: 'GCD & LCM', category: 'math'},
  { id: 'standard-deviation', title: 'Standard Deviation', category: 'math'},
  { id: 'kinetic-energy', title: 'Kinetic Energy', category: 'math'},
  { id: 'potential-energy', title: 'Potential Energy', category: 'math'},
  { id: 'ohm-law', title: 'Ohms Law', category: 'math'},
  { id: 'power', title: 'Power (Electrical)', category: 'math'},
  { id: 'density', title: 'Density', category: 'math'},
  { id: 'force', title: 'Force (F=ma)', category: 'math'},
  { id: 'speed-distance-time', title: 'Speed / Dist / Time', category: 'math'},
  { id: 'present-value', title: 'Present Value', category: 'finance'},
  { id: 'future-value', title: 'Future Value', category: 'finance'},
  { id: 'apy', title: 'APY Calculator', category: 'finance'},
  { id: 'current-yield', title: 'Current Yield (Bond)', category: 'finance'},
  { id: 'dividend-yield', title: 'Dividend Yield', category: 'finance'},
  { id: 'wacc', title: 'WACC', category: 'business'},
  { id: 'current-ratio', title: 'Current Ratio', category: 'business'},
  { id: 'quick-ratio', title: 'Quick Ratio', category: 'business'},
  { id: 'debt-to-equity', title: 'Debt to Equity', category: 'business'},
  { id: 'bra-size', title: 'Bra Size', category: 'lifestyle'},
  { id: 'shoe-size-converter', title: 'Shoe Size Converter', category: 'lifestyle'},
  { id: 'temperature-converter', title: 'Temp Converter', category: 'lifestyle'},
  { id: 'weight-converter', title: 'Weight Converter', category: 'lifestyle'},
  { id: 'data-storage-converter', title: 'Data Converter', category: 'lifestyle'},
  { id: 'dog-age', title: 'Dog Age', category: 'lifestyle'},
  { id: 'cat-age', title: 'Cat Age', category: 'lifestyle'},
  { id: 'energy-cost', title: 'Energy Cost', category: 'lifestyle'},
  { id: 'pool-volume', title: 'Pool Volume', category: 'lifestyle'},
  { id: 'concrete-volume', title: 'Concrete Calculator', category: 'lifestyle'},
  { id: 'paint', title: 'Paint Calculator', category: 'lifestyle'},
  { id: 'roofing', title: 'Roofing Calculator', category: 'lifestyle'},
  { id: 'z-score', title: 'Z-Score', category: 'math'},
  { id: 'expected-value', title: 'Expected Value', category: 'math'},
  { id: 'roman-numerals', title: 'Roman Numerals', category: 'lifestyle'},
  
  { id: 'ratio', title: 'Ratio Calculator', category: 'math'},
  { id: 'percentage-diff', title: 'Percentage Difference', category: 'math'},
  { id: 'percentage-error', title: 'Percentage Error', category: 'math'},
  { id: 'fraction-decimal', title: 'Fraction to Decimal', category: 'math'},
  { id: 'triangle-area', title: 'Triangle Area', category: 'math'},
  { id: 'rectangle-area', title: 'Rectangle Area', category: 'math'},
  { id: 'circle-circumference', title: 'Circle Circumference', category: 'math'},
  { id: 'arc-length', title: 'Arc Length', category: 'math'},
  { id: 'sector-area', title: 'Sector Area', category: 'math'},
  { id: 'sphere-surface-area', title: 'Sphere Surface Area', category: 'math'},
  { id: 'cylinder-surface-area', title: 'Cylinder Surface Area', category: 'math'},
  { id: 'box-surface-area', title: 'Box Surface Area', category: 'math'},
  { id: 'margin-of-error', title: 'Margin of Error', category: 'math'},
  { id: 'rule-of-72', title: 'Rule of 72', category: 'finance'},
  { id: 'sales-tax', title: 'Sales Tax', category: 'tax'},
  { id: 'vat', title: 'VAT Calculator', category: 'tax'},
  { id: 'profit-percentage', title: 'Profit Percentage', category: 'business'},
  { id: 'revenue', title: 'Revenue Calculator', category: 'business'},
  { id: 'net-income', title: 'Net Income', category: 'business'},
  { id: 'inventory-turnover', title: 'Inventory Turnover', category: 'business'},
  { id: 'days-in-inventory', title: 'Days in Inventory', category: 'business'},
  { id: 'receivables-turnover', title: 'Receivables Turnover', category: 'business'},
  { id: 'return-on-assets', title: 'Return on Assets', category: 'business'},
  { id: 'return-on-equity', title: 'Return on Equity (ROE)', category: 'business'},
  { id: 'calorie-deficit', title: 'Calorie Deficit', category: 'health'},
  { id: 'run-pace', title: 'Running Pace', category: 'health'},
  { id: 'ideal-weight', title: 'Ideal Weight', category: 'health'},
  { id: 'water-intake', title: 'Water Intake', category: 'health'},
  { id: 'blood-donation', title: 'Blood Donation Date', category: 'health'},
  { id: 'velocity-calc', title: 'Velocity (Distance/Time)', category: 'math'},
  { id: 'torque-calc', title: 'Torque', category: 'math'},
  { id: 'mass-energy', title: 'E=mc²', category: 'math'},
  { id: 'hookes-law', title: 'Hookes Law', category: 'math'},
  { id: 'kinetic-friction', title: 'Kinetic Friction', category: 'math'},
  { id: 'escape-velocity', title: 'Escape Velocity', category: 'math'},
  { id: 'decimal-binary', title: 'Decimal to Binary', category: 'lifestyle'},
  { id: 'decimal-hex', title: 'Decimal to Hex', category: 'lifestyle'},
  { id: 'binary-decimal', title: 'Binary to Decimal', category: 'lifestyle'},
  { id: 'hex-decimal', title: 'Hex to Decimal', category: 'lifestyle'},
  { id: 'base64-encode', title: 'Base64 Encode', category: 'lifestyle'},
  { id: 'words-calculator', title: 'Word Count Calculator', category: 'lifestyle'},
  { id: 'time-duration', title: 'Time Duration', category: 'lifestyle'},
  { id: 'days-between', title: 'Days Between', category: 'lifestyle'},
  { id: 'timestamp-date', title: 'Timestamp to Date', category: 'lifestyle'},
  { id: 'adding-time', title: 'Add Time', category: 'lifestyle'},
  { id: 'scientific-notation', title: 'Scientific to Dec', category: 'math'},
  { id: 'molar-mass', title: 'Molar Mass (H2O)', category: 'math'},
  { id: 'moles', title: 'Moles (H2O)', category: 'math'},
];

let constantsCode = fs.readFileSync('src/constants.ts', 'utf8');

const toInjectConstants = c1.map(c => 
  `  { id: '${c.id}', title: '${c.title}', slug: '${c.id}-calculator', description: '${c.title} calculator.', category: '${c.category}', priority: 'P3', icon: 'Calculator', formula: '', howItWorks: [], faqs: [], countryTips: [], relatedSlugs: [], seoTitle: '', seoDescription: '' },`
).join('\n');

constantsCode = constantsCode.replace(
  /export const CALCULATORS: CalculatorMetadata\[\] = \[\n/,
  `export const CALCULATORS: CalculatorMetadata[] = [\n` + toInjectConstants + `\n`
);
fs.writeFileSync('src/constants.ts', constantsCode);

console.log('Fixed constants');
